### PR TITLE
Update to 0.7.4

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes https://github.com/conda-forge/openlibm-feedstock/pull/17

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by ngam** [comment]
@izahn any hope for fixing the PRs here? We want to add OSXARM support to julia and this is a dependency.

**Comment by izahn** [comment]
I probably won’t get a chance to look at it until after the new year. Happy to review PRs if someone wants to take a crack at it before then.

**Comment by ngam** [comment]
@izahn going for v0.8.0 here. I am giving up on windows tho, so if you care about windows you should try to build it. Do you want to be added here as maintainer?

https://github.com/conda-forge/openlibm-feedstock/pull/25

**Comment by izahn** [comment]
> @izahn going for v0.8.0 here. I am giving up on windows tho, so if you care about windows you should try to build it. Do you want to be added here as maintainer?
> 
> #25

OK good luck! I've kind of lost my motivation for this one since I've given up on getting julia working properly from conda-forge for the time being. No need to add me as a maintainer here.

**Comment by ngam** [comment]
> getting julia working properly from conda-forge

It depends on what you mean "properly" but we've made some progress and I think we are in a much better position now than a few weeks ago. You should keep an eye (or rather, keep that feedstock in your peripheral vision). Mkitti and are pushing hard (though I am significantly less knowledgable about julia than mkitti...)

I believe we have a good enough setup for an isolated julia that should function pretty solidly. Having julia do packaging and all that --- including sharing binaries, etc. --- is a whole different story

**Comment by ngam** [comment]
Closing this, feel free to open again or file another issue

**Comment by mkitti** [comment]
We need 1.7.4 for Linux and macOS, so I suggest merging this and skipping Windows for now.

**Pull request closed without merging**
