### PR TITLE
Add SylvainCorlay to maintainer list

### PR DESCRIPTION
**Pull request by SylvainCorlay**
In order to work on the rebuild of earlier versions.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Not merging @dfornika ?

**Comment by SylvainCorlay** [comment]
Ah it seems a duplicate was merged.

**Comment by jakirkham** [comment]
The [commit's in `master`]( https://github.com/conda-forge/openlibm-feedstock/commit/bc524245c137c7732a80d8a4b7feb30c11ec6079 ). Just think GitHub's very confused ATM.

**Comment by dfornika** [comment]
Yes, I saw that it was merged so that's why I closed this. Sorry, I should have left a message explaining that.

**Comment by jakirkham** [comment]
Manually retriggered the webhook. Looks like the bot added you. Welcome 😄

**Pull request closed without merging**
