### PR TITLE
Patch cc

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Test rebuild

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...on my phone so may be missing something, but it seems like the patch didn’t get included.

**Comment by SylvainCorlay** [comment]
Indeed, the patch was not included earlier.
This appears to be working now!

**Comment by SylvainCorlay** [comment]
@jakirkham feel like merging?

**Comment by jakirkham** [comment]
Thanks @SylvainCorlay 😄

**Pull request merged**
